### ISSUE TITLE
How use absolute path?

### ISSUE THREAD

**Issue by sergioplaza** [Elendev/ElendevRoxyFilemanBundle#5]
Hi, I want to use absolute path, where can I change this configuration ?
Regards.

**Comment by Elendev** [comment]
Hi, are you talking about the local_file_system.base_path configuration ? If it's the case, it can be an absolute path

**Comment by Elendev** [comment]
Can I close this issue ?

**Comment by sergioplaza** [comment]
Yes, thank you for your help.
